name = "hugo-shortcode-gallery"
license = "MIT"
licenselink = "https://github.com/raphael-milliere/hugo-shortcode-gallery/blob/master/LICENSE.md"
description = "A theme component with a gallery shortcode for the static site generator hugo."
homepage = "https://github.com/raphael-milliere/hugo-shortcode-gallery"
demosite = "https://matze.rocks/images"
tags = ["Gallery", "Responsive", "Shortcode"]
min_version = "0.121.2"

[author]
  name = "raphael-milliere"
  homepage = "https://matze.rocks"
